apiVersion: v1
kind: Service
metadata:
  name: sm-lobby-pad-service
spec:
  selector:
    app: sm-lobby-pad
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sm-lobby-pad-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sm-lobby-pad-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-lobby-pad
  labels:
    app: sm-lobby-pad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-lobby-pad
  template:
    metadata:
      labels:
        app: sm-lobby-pad
    spec:
      volumes:
        - name: sm-lobby-pad-storage
          persistentVolumeClaim:
            claimName: sm-lobby-pad-volume-claim
        - name: secrets
          secret:
            secretName: lobby-pad-secrets
      containers:
        - name: sm-lobby-pad-container
          image: scoizzle/lobby-pad:0.0.9
          ports:
            - containerPort: 5000
              name: "app-server"
          volumeMounts:
            - mountPath: "/app/data"
              name: sm-lobby-pad-storage
            - name: secrets
              mountPath: /app/secrets
              readOnly: true